// Code generated by internal/genparams from Params.java. DO NOT EDIT.
//
// Regenerate with: go generate ./...

package main

// Params maps every parameter name the phone accepts to where it takes effect.
// Decision D9: camera state persists, presentation lives for one request.
var Params = map[string]Kind{
	"_":           Router,
	"ae":          Camera,
	"aelock":      Camera,
	"af":          Camera,
	"awb":         Camera,
	"awblock":     Camera,
	"cam":         Camera,
	"camera":      Camera,
	"cx":          Camera,
	"cy":          Camera,
	"dx":          Camera,
	"dy":          Camera,
	"ev":          Camera,
	"exposure":    Camera,
	"focus":       Camera,
	"focusm":      Camera,
	"format":      Router,
	"fps":         Router,
	"fresh":       Router,
	"h":           Presentation,
	"iso":         Camera,
	"jpegq":       Presentation,
	"measure":     Camera,
	"n":           Router,
	"port":        Router,
	"previewsize": Camera,
	"quality":     Presentation,
	"reset":       Router,
	"rotate":      Camera,
	"sensitivity": Camera,
	"settle":      Router,
	"shadingmap":  Camera,
	"sharpness":   Router,
	"shutter":     Camera,
	"stillsize":   Camera,
	"t":           Router,
	"timeout":     Router,
	"torch":       Camera,
	"w":           Presentation,
	"wait":        Router,
	"zoom":        Camera,
	"zoomby":      Camera,
}
