// Command genparams writes params_gen.go from the phone's parameter declarations.
//
// Params.java is the one place a parameter name exists. The Java parser reads it, the
// phone's /api/help is printed from it, the Python contract test holds the documents to
// it, and this makes the Go client read the same list rather than becoming a fifth copy
// that drifts. Run it with `go generate ./...`.
//
// Only names and kinds are taken. Help text stays on the phone, where `deskcam api`
// fetches it live, because a client that ships its own copy of the documentation is
// exactly the thing this avoids.
package main

import (
	"fmt"
	"log"
	"os"
	"regexp"
	"sort"
	"strings"
)

var (
	call    = regexp.MustCompile(`(?m)^ {8}(camera|presentation|router)\(`)
	trailer = regexp.MustCompile(`((?:"[a-z_]{1,16}"\s*,\s*)*"[a-z_]{1,16}")\s*\);`)
	literal = regexp.MustCompile(`"([a-z_]+)"`)
)

func main() {
	if len(os.Args) != 3 {
		log.Fatal("usage: genparams <Params.java> <output.go>")
	}
	source, err := os.ReadFile(os.Args[1])
	if err != nil {
		log.Fatal(err)
	}
	body := string(source)
	start := strings.Index(body, "static {")
	end := strings.Index(body, "\n    public static P get(")
	if start < 0 || end < 0 {
		log.Fatal("cannot find the declaration block; has Params.java been reshaped?")
	}
	body = body[start:end]

	found := call.FindAllStringSubmatchIndex(body, -1)
	if len(found) == 0 {
		log.Fatal("no parameter declarations found")
	}

	type entry struct{ name, kind string }
	var entries []entry
	seen := map[string]bool{}
	for i, m := range found {
		stop := len(body)
		if i+1 < len(found) {
			stop = found[i+1][0]
		}
		chunk := body[m[0]:stop]
		kind := body[m[2]:m[3]]
		tail := trailer.FindStringSubmatch(chunk)
		if tail == nil {
			log.Fatalf("cannot read the names out of: %.60q", chunk)
		}
		for _, n := range literal.FindAllStringSubmatch(tail[1], -1) {
			if seen[n[1]] {
				log.Fatalf("parameter %q is declared twice", n[1])
			}
			seen[n[1]] = true
			entries = append(entries, entry{n[1], kind})
		}
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].name < entries[j].name })

	var out strings.Builder
	out.WriteString("// Code generated by internal/genparams from Params.java. DO NOT EDIT.\n")
	out.WriteString("//\n")
	out.WriteString("// Regenerate with: go generate ./...\n\n")
	out.WriteString("package main\n\n")
	out.WriteString("// Params maps every parameter name the phone accepts to where it takes effect.\n")
	out.WriteString("// Decision D9: camera state persists, presentation lives for one request.\n")
	out.WriteString("var Params = map[string]Kind{\n")
	width := 0
	for _, e := range entries {
		if len(e.name)+2 > width {
			width = len(e.name) + 2
		}
	}
	for _, e := range entries {
		kind := map[string]string{
			"camera": "Camera", "presentation": "Presentation", "router": "Router",
		}[e.kind]
		out.WriteString(fmt.Sprintf("\t%-*s %s,\n", width+1, `"`+e.name+`":`, kind))
	}
	out.WriteString("}\n")

	if err := os.WriteFile(os.Args[2], []byte(out.String()), 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("genparams: %d names written to %s\n", len(entries), os.Args[2])
}
